# Generated by Django 5.2.2 on 2025-06-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=80)),
                ('member_email', models.EmailField(max_length=80, unique=True)),
                ('member_phone', models.CharField(max_length=11, unique=True)),
                ('member_type', models.CharField(choices=[('default', 'Padrão'), ('social', 'Social'), ('public', 'Público')])),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('member_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['member_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_code', models.CharField(max_length=128, unique=True)),
                ('book_year', models.IntegerField(blank=True, null=True)),
                ('book_genre', models.CharField(choices=[('romance', 'Romance'), ('poesia', 'Poesia'), ('ficcao_cientifica', 'Ficção Científica'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('misterio', 'Mistério'), ('terror', 'Terror'), ('cronica', 'Crônica'), ('novela', 'Novela')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['book_name'],
            },
        ),
    ]
