# Generated by Django 5.2.2 on 2025-06-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=80)),
                ('book_code', models.CharField(max_length=128)),
                ('book_year', models.IntegerField(blank=True, null=True)),
                ('book_genre', models.CharField(choices=[('romance', 'Romance'), ('poesia', 'Poesia'), ('ficcao_cientifica', 'Ficção Científica'), ('fantasia', 'Fantasia'), ('suspense', 'Suspense'), ('misterio', 'Mistério'), ('terror', 'Terror'), ('cronica', 'Crônica'), ('novela', 'Novela')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
    ]
